/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as MusikRouteImport } from './routes/musik'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as SongtexteRouteImport } from './routes/songtexte'
import { Route as SpotifyRouteImport } from './routes/spotify'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiYtThumbIdRouteImport } from './routes/api/yt-thumb.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const MusikRoute = MusikRouteImport.update({
  id: '/musik',
  path: '/musik',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const SongtexteRoute = SongtexteRouteImport.update({
  id: '/songtexte',
  path: '/songtexte',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyRoute = SpotifyRouteImport.update({
  id: '/spotify',
  path: '/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYtThumbIdRoute = ApiYtThumbIdRouteImport.update({
  id: '/api/yt-thumb/$id',
  path: '/api/yt-thumb/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fotos': typeof FotosRoute
  '/impressum': typeof ImpressumRoute
  '/musik': typeof MusikRoute
  '/songs': typeof SongsRoute
  '/songtexte': typeof SongtexteRoute
  '/spotify': typeof SpotifyRoute
  '/videos': typeof VideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/yt-thumb/$id': typeof ApiYtThumbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fotos': typeof FotosRoute
  '/impressum': typeof ImpressumRoute
  '/musik': typeof MusikRoute
  '/songs': typeof SongsRoute
  '/songtexte': typeof SongtexteRoute
  '/spotify': typeof SpotifyRoute
  '/videos': typeof VideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/yt-thumb/$id': typeof ApiYtThumbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fotos': typeof FotosRoute
  '/impressum': typeof ImpressumRoute
  '/musik': typeof MusikRoute
  '/songs': typeof SongsRoute
  '/songtexte': typeof SongtexteRoute
  '/spotify': typeof SpotifyRoute
  '/videos': typeof VideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/yt-thumb/$id': typeof ApiYtThumbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/fotos'
    | '/impressum'
    | '/musik'
    | '/songs'
    | '/songtexte'
    | '/spotify'
    | '/videos'
    | '/blog/$slug'
    | '/blog/'
    | '/api/yt-thumb/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/fotos'
    | '/impressum'
    | '/musik'
    | '/songs'
    | '/songtexte'
    | '/spotify'
    | '/videos'
    | '/blog/$slug'
    | '/blog'
    | '/api/yt-thumb/$id'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/fotos'
    | '/impressum'
    | '/musik'
    | '/songs'
    | '/songtexte'
    | '/spotify'
    | '/videos'
    | '/blog/$slug'
    | '/blog/'
    | '/api/yt-thumb/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FotosRoute: typeof FotosRoute
  ImpressumRoute: typeof ImpressumRoute
  MusikRoute: typeof MusikRoute
  SongsRoute: typeof SongsRoute
  SongtexteRoute: typeof SongtexteRoute
  SpotifyRoute: typeof SpotifyRoute
  VideosRoute: typeof VideosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiYtThumbIdRoute: typeof ApiYtThumbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musik': {
      id: '/musik'
      path: '/musik'
      fullPath: '/musik'
      preLoaderRoute: typeof MusikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songtexte': {
      id: '/songtexte'
      path: '/songtexte'
      fullPath: '/songtexte'
      preLoaderRoute: typeof SongtexteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotify': {
      id: '/spotify'
      path: '/spotify'
      fullPath: '/spotify'
      preLoaderRoute: typeof SpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yt-thumb/$id': {
      id: '/api/yt-thumb/$id'
      path: '/api/yt-thumb/$id'
      fullPath: '/api/yt-thumb/$id'
      preLoaderRoute: typeof ApiYtThumbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  FotosRoute: FotosRoute,
  ImpressumRoute: ImpressumRoute,
  MusikRoute: MusikRoute,
  SongsRoute: SongsRoute,
  SongtexteRoute: SongtexteRoute,
  SpotifyRoute: SpotifyRoute,
  VideosRoute: VideosRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiYtThumbIdRoute: ApiYtThumbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
